/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'coverImageUrl' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [IDL.Int],
      [],
    ),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPostForEditAdmin' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
  'getPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'publishPost' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unpublishPost' : IDL.Func([IDL.Nat], [], []),
  'updatePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'coverImageUrl' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [IDL.Int],
        [],
      ),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPostById' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPostForEditAdmin' : IDL.Func([IDL.Nat], [IDL.Opt(Post)], ['query']),
    'getPublishedPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'publishPost' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unpublishPost' : IDL.Func([IDL.Nat], [], []),
    'updatePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };